cursor #e5e1e2
cursor_text_color #c8c5cc

foreground            #e5e1e2
background            #141314
selection_foreground  #303035
selection_background  #c8c5cc
url_color             #c7c5d4

color0   #141314
color1   #f36d8b
color2   #6ad47e
color3   #ffd972
color4   #bab8c9
color5   #575562
color6   #c7c5d4
color7   #d3d1de
color8   #817f89
color9   #ff9fb4
color10  #a5feb6
color11  #ffe7a5
color12  #dddbe9
color13  #f4f2ff
color14  #f7f6ff
color15  #f9f8ff
