#!/bin/bash
sudo apt install curl

# nodejs
sudo apt-get install -y curl
curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
sudo apt-get install -y nsolid
nsolid -v

# protonvpn
wget https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.8_all.deb

# install uv
curl -LsSf https://astral.sh/uv/install.sh | sh

sudo dpkg -i ./protonvpn-stable-release_1.0.8_all.deb && sudo apt update

# installs deb-get
sudo apt install curl lsb-release wget
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get

# installs topgrade
deb-get install topgrade

# brave-bin
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
sudo curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
sudo apt update
sudo apt install brave-browser

# pacstall
sudo bash -c "$(curl -fsSL https://pacstall.dev/q/install)"

# rustup
