[mgr]
linemode = "size"
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true

[[open.rules]]
name = "*/"
use = "edit"

[[open.rules]]
mime = "text/*"
use = "edit"

[[open.rules]]
mime = "image/*"
use = "image"

[[open.rules]]
mime = "video/*"
use = "video"

[[open.rules]]
mime = "audio/*"
use = "audio"

[[open.rules]]
mime = "application/pdf"
use = "document"

[[open.rules]]
mime = "application/*zip"
use = "archive"

[[open.rules]]
mime = "application/x-tar"
use = "archive"

[[open.rules]]
mime = "application/x-bzip2"
use = "archive"

[[open.rules]]
mime = "application/x-7z-compressed"
use = "archive"

[[open.rules]]
name = "*"
use = "fallback"

[[opener.archive]]
desc = "Extract with File Roller"
run = "/nix/store/5a9dg0kvwxyg1dga1fhycak9a4q3kvk3-file-roller-44.5/bin/file-roller \"$@\""

[[opener.archive]]
desc = "Extract with ouch"
run = "ouch decompress \"$@\""

[[opener.audio]]
desc = "Play with mpv"
run = "mpv \"$@\""

[[opener.document]]
desc = "View with Zathura"
run = "/nix/store/kz12lgzd1gbgmrj4kfkhdnji77hwqrxr-zathura-with-plugins-0.5.13/bin/zathura \"$@\""

[[opener.edit]]
block = true
desc = "Edit with Neovim"
run = "nvim \"$@\""

[[opener.fallback]]
desc = "Open with default application"
run = "/nix/store/14vf9i1yp5s4x1wmginjbimgls1hvbm5-xdg-utils-1.2.1/bin/xdg-open \"$@\""

[[opener.image]]
desc = "View with imv"
run = "imv \"$@\""

[[opener.video]]
block = false
desc = "Play with mpv"
orphan = true
run = "mpv \"$@\""

[[plugin.prepend_previewers]]
name = "*.md"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.json"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.csv"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.rst"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.ipynb"
run = "rich-preview"

[[plugin.prepend_previewers]]
mime = "application/*zip"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-tar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-bzip2"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-7z-compressed"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-rar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-xz"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-zstd"
run = "ouch"

[preview]
cache_dir = ""
max_height = 1000
max_width = 1000
