# Do not source variables
# make sure add an exec for colors

# Main settings
source = $hl/autostart.conf
source = $hl/env.conf
source = $hl/keybindings.conf
source = $hl/monitor.conf
source = $hl/plugins.conf
source = $hl/rules.conf
source = $hl/settings.conf


