aliases:
  auth-common: auth switch --hostname github.com --user aahsnr-common
  auth-configs: auth switch --hostname github.com --user aahsnr-configs
  auth-peronal: auth switch --hostname github.com --user aahsnr-personal
  auth-work: auth switch --hostname github.com --user aahsnr-work
editor: nvim
git_protocol: ssh
version: '1'
